{% set name = "signac-dashboard" %}
{% set version = "0.5.0" %}
{% set sha256 = "daf24b89de72633945b96b31819fb451cf6059c780b012c12acf36135f8f201f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/signac-dashboard/signac-dashboard-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - flask >=2.1.0
    - flask-assets >=2.0.0
    - flask-login >=0.6.0
    - flask-turbolinks
    - jinja2 >=3.0.0
    - jsmin
    - libsass
    - markupsafe >=2.0.0
    - natsort
    - python >=3.8
    - signac >=1.8.0
    - watchdog
    - webassets >=2.0.0
    - werkzeug >=2.1.0

test:
  imports:
    - signac_dashboard

about:
  home: https://signac.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'signac-dashboard: data visualization for signac'
  description: |
    Built on top of the signac framework, signac-dashboard allows
    users to rapidly visualize and analyze data managed in a signac
    project.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac-dashboard

extra:
  recipe-maintainers:
    - csadorf
    - bdice
    - cbkerr
