appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jm4qzVfq2gXZ+kklZI6gaMoEuNXQRsIjkSHSeOJc4HrsYNe+N4GwXTp/YtT9Z7Kw4ePCgoXrYiiHlW+X11XgxAXeEQCmV+15FJC2fGN13wl905bQJevqDh7veRCDM1znh0ZMpohjEyAiSp7PwGAsUonPbU5r/uk0xCfRgeyQeV6t15is4G4Gsp/mkO7Z+8eg5DC2OyK4eX0+mlh8oLa6q8dDqhzkLuc87LaPvM9eKJJg4Af2TAcqKIeJp99UkeBjCtH5KDEjZeXa2IZkNgd4XAa6WETqoK69jG8sAnp0oDI4VYWgrgfaw9lUz6oCRU0PW5WtCVKIh+wDsR8vUOAR+UUhtjsPTkYds7s/qmRHNhdQ9N1gY5Fv+WPVfyPjqzHz0SB4ujKu2Lm/yKKUKy5ien7MtfiLJeeRs2LgF7HaFDRldMVG644UdeyRUIz4d/z5xRNaF7nJVVvRWec/+DtsJBVR7Nd1/rc1JZMQjuUEJ7aU7YFyr6pkDKjEaihgXsXaPyusrN0ni8pZcIC10mASQ0H9rdLy6ls8O8K9Kb6r3bmGAumwCAYVsahbt/B4/mwih74sei5Ksv9d1Y64l4CMB2cX7osTEbPVtU3vWTcmlSPAgyyV+gAWnUTNeZvfElH885xj/h8141lg1ZBbd85/hcpBd4XFNcwxGwNdikr7M9g=}
provider:
  win: azure
conda_forge_output_validation: false
